[build]
    publish = "./dist"
    command = "npx npm-force-resolutions && npm run build"    

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        Content-Security-Policy = """
            frame-ancestors 'none'
        """

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200